# docker-compose.yml
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    container_name: weaviate
    restart: on-failure:0          # keep it up but don’t loop forever
    ports:
      - "8080:8080"                # HTTP / GraphQL / REST
      - "50051:50051"              # gRPC
    environment:
      # --- basic server -----------------------------------
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      ENABLE_API_BASED_MODULES: "true"
      CLUSTER_HOSTNAME: "node1"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      # --- memory‑friendly tweaks --------------------------
      LIMIT_RESOURCES: "true"
      GODEBUG: "madvdontneed=1"
    volumes:
      - ./weaviate-data:/var/lib/weaviate   # persistent index & metadata
    deploy:                                 # put a 1 GB RAM cap on the container
      resources:
        limits:
          memory: 1G